version: "3.9"

services:
  prod:
    image:
    container_name: tracking-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    env_file:
      - .env
    command: npm run start
