name: "configure-aws-ecr"
description: "Configure AWS credentials and login to ECR"

outputs:
  registry:
    description: "The target ecr registry"
    value: ${{ steps.login-ecr.outputs.registry }}
inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
